// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModlist(arg1) {
  return window['go']['main']['App']['DeleteModlist'](arg1);
}

export function GetModlistImageBase64(arg1, arg2) {
  return window['go']['main']['App']['GetModlistImageBase64'](arg1, arg2);
}

export function GetModlists() {
  return window['go']['main']['App']['GetModlists']();
}

export function ProcessWabbajackFile() {
  return window['go']['main']['App']['ProcessWabbajackFile']();
}
