// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModlist(arg1) {
  return window['go']['main']['App']['DeleteModlist'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetModlistById(arg1) {
  return window['go']['main']['App']['GetModlistById'](arg1);
}

export function GetModlistImageBase64(arg1, arg2) {
  return window['go']['main']['App']['GetModlistImageBase64'](arg1, arg2);
}

export function GetModlists() {
  return window['go']['main']['App']['GetModlists']();
}

export function GetModsByProfileId(arg1) {
  return window['go']['main']['App']['GetModsByProfileId'](arg1);
}

export function GetProfileFilesByProfileId(arg1) {
  return window['go']['main']['App']['GetProfileFilesByProfileId'](arg1);
}

export function GetProfilesByModlistId(arg1) {
  return window['go']['main']['App']['GetProfilesByModlistId'](arg1);
}

export function ProcessWabbajackFile() {
  return window['go']['main']['App']['ProcessWabbajackFile']();
}
