// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {models} from '../models';

export function ApplyBinaryPatch(arg1:string,arg2:string):Promise<void>;

export function DeleteModlist(arg1:string):Promise<void>;

export function DetectFomodOptions(arg1:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function GetModArchivesByModId(arg1:string):Promise<Array<dtos.ModArchiveDTO>>;

export function GetModFilesByModId(arg1:string):Promise<Array<dtos.ModFileDTO>>;

export function GetModlistById(arg1:string):Promise<dtos.ModlistDTO>;

export function GetModlistImageBase64(arg1:string,arg2:string):Promise<string>;

export function GetModlists():Promise<Array<dtos.ModlistDTO>>;

export function GetModsByProfileId(arg1:string):Promise<Array<dtos.GroupedModDTO>>;

export function GetProfileFilesByProfileId(arg1:string):Promise<Array<models.ProfileFile>>;

export function GetProfilesByModlistId(arg1:string):Promise<Array<models.Profile>>;

export function ProcessWabbajackFile():Promise<void>;
