// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {models} from '../models';

export function DeleteModlist(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function GetModlistById(arg1:string):Promise<dtos.ModlistDTO>;

export function GetModlistImageBase64(arg1:string,arg2:string):Promise<string>;

export function GetModlists():Promise<Array<dtos.ModlistDTO>>;

export function GetProfileFilesByProfileId(arg1:string):Promise<Array<models.ProfileFile>>;

export function GetProfilesByModlistId(arg1:string):Promise<Array<models.Profile>>;

export function ProcessWabbajackFile():Promise<void>;
