// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';

export function DeleteModlist(arg1:string):Promise<void>;

export function GetModlistImageBase64(arg1:string,arg2:string):Promise<string>;

export function GetModlists():Promise<Array<dtos.ModlistDTO>>;

export function ProcessWabbajackFile():Promise<void>;
